# Makefile for a cc3 project
# C files to compile
CSOURCES=new_main.c cc3_func.c
# header files
INCLUDES=cc3_func.h
# header files
LIBS=cc3-ilp
# the name of this project
PROJECT=PPE
# the makefile is useless without the next line!
include ../../include/common.mk
